---
version: "3.7"
services:
  load_conf_json:
    build: "."
    image: "load_configuration:latest"
    volumes:
      - type: bind
        source: "."
        target: "/src"
    command: python load_conf_to_json.py
    
  load_conf_yaml:
    build: "."
    image: "load_configuration:latest"
    volumes:
      - type: bind
        source: "."
        target: "/src"
    command: python load_conf_to_yaml.py